services:
  angular:
    container_name: country-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - country-net

# network bridge
networks:
  country-net:
    external: true
