name: country
services:
  angular:
    container_name: country-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

# network bridge
networks:
  app-network:
    external: true
