name: country-ui
services:
  angular:
    container_name: angular
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - country-network

# network bridge
networks:
  country-network:
    external: true
