name: country
services:
  angular-ui:
    container_name: country-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

# allows network communication across different containers
# the other container (spring-boot) must also implement
# the same network bridge
#networks:
#  country-network:
#    external: true
